model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='ST2 (IL-33R) [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='ST2 (IL-33R) [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='ST2 (IL-33R) [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='ST2 (IL-33R) [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='ST2 (IL-33R) [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='ST2 (IL-33R) [NSU]'
