model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='IL-15_IL-15R alpha complex [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='IL-15_IL-15R alpha complex [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='IL-15_IL-15R alpha complex [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='IL-15_IL-15R alpha complex [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='IL-15_IL-15R alpha complex [NSU]'
model_type='final'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='IL-15_IL-15R alpha complex [NSU]'
