model_type='shuffled_baseline'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='XCL1 (Lymphotactin) [NSU]'
model_type='shuffled_baseline'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='XCL1 (Lymphotactin) [NSU]'
model_type='shuffled_baseline'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='XCL1 (Lymphotactin) [NSU]'
model_type='shuffled_baseline'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='XCL1 (Lymphotactin) [NSU]'
model_type='shuffled_baseline'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='XCL1 (Lymphotactin) [NSU]'
model_type='shuffled_baseline'
control='DMSO_0.100_DMSO_0.025'
treatments='LPS_100.000_DMSO_0.025'
aggregation=True
nomic=True
cell_type='SHSY5Y'
feature='XCL1 (Lymphotactin) [NSU]'
