[MACHINE_LEARNING_PARAMS]
# option for MODEL_TYPE are: ["Regression", "Binary_Classification", "Multi_Class"]
MODEL_TYPE = "Multi_Class"
DATA_SUBSET_OPTION = "False"
DATA_SUBSET_NUMBER = 5000
BATCH_SIZE = 32
HYPERPARAMETER_BATCH_SIZE = 100
TRAIN_PROPORTION_SPLIT = 0.8
VALIDATION_PROPORTION_SPLIT = 0.1
TEST_PROPORTION_SPLIT = 0.1
OPTIM_EPOCHS = 50
N_TRIALS = 50
TRAIN_EPOCHS = 100
MIN_LAYERS = 1
MAX_LAYERS = 15
LAYER_UNITS_MIN = 2
LAYER_UNITS_MAX = 50
DROPOUT_MIN = 0.1
DROPOUT_MAX = 0.4
DROP_OUT_STEP = 0.05
LEARNING_RATE_MIN = 1e-5
LEARNING_RATE_MAX = 0.1
OPTIMIZER_LIST = [ "Adam", "RMSprop", "SGD" ]
METRIC = "loss"
DIRECTION = "minimize"
MODEL_NAME = "DMSO_0.025_vs_LPS_100"
CONTROL_NAME = "DMSO_0.100_%_DMSO_0.025_%"
TREATMENT_NAME = "LPS_100.000_ug_per_ml_DMSO_0.025_%"
CELL_TYPE = "PBMC"
SHUFFLE = "False"
