[list_of_treatments]
treatments=[
    'DMSO__0.100__DMSO__0.025',

 'Flagellin__0.100__DMSO__0.025',
 'Flagellin__1.000__DMSO__0.025',
 'LPS__0.010__DMSO__0.025',
 'LPS_1.000__DMSO__0.025',
 'LPS__100.000__DMSO__0.025',
 'LPS_Nigericin__1.000_1.000__DMSO__0.025',
 'LPS_Nigericin__1.000_3.000__DMSO__0.025',
 'LPS_Nigericin__1.000_10.000__DMSO__0.025',

 'Thapsigargin__1.000__DMSO__0.025',
 'Thapsigargin__10.000__DMSO__0.025',

 'H2O2__100.000__DMSO__0.025',


]
