[logistic_regression_params]
MODEL_TYPE="Multi_Class"
control="DMSO_0.100_DMSO_0.025"
treatments=["LPS_10.000_DMSO_0.025", "LPS_100.000_DMSO_0.025"]
aggregation="False"
nomic="True"
cell_type="SHSY5Y"
